/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
/* Used to be YUFA.h which was generated from YUFA.idl.
 * Note: this file is now fixed and not to be generated anymore
         It has been renamed for this purpose to YUFlatArray.h to enforce this.
         Existing files should include YUFlatArray.h NOT YUFA.h!
*/

#ifndef YUFA_v0_0_included
#define YUFA_v0_0_included

#ifdef __cplusplus
    extern "C" {
#endif

typedef struct YUFlatArray {
   long int size; // number of characters allocated in data[]
   char data[1];  // don't be misled by the definition of one byte - this is variable sized storage usually allocated by malloc() or similar
                  // e.g. yf.data = malloc(1000)
} YUFlatArray;

#ifdef __cplusplus
}
#endif

#endif
